server:
  port: 8030
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: spring-cloud-eureka-user-hystrix
